name: aimg
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Python Setup Tools
        run: pip --cache-dir=pipcache install setuptools
      - name: Setup pip cache
        run: pip --cache-dir=pipcache install -r requirments.txt
      - name: Install imaginAIry
        run: pip --cache-dir=pipcache install imaginAIry
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: pip
            path: pipcache
      - name: Create test png via AI
        run: sh aimg.sh imagine "cheese in the eifel tower"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: outputs
