name: aimg
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: linux-latest
    container: devkitpro:latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Directory Contents
        run: ls
      - name: Read the desired prompt
        run: export prompt="cheese in the eifel tower"
      - name: Echo/readback/printout the entered prompt
        run: echo ${prompt}
      - name: Install python
        run: apt install -y python
      - name: Install requirements
        run: pip install -r imaginAIry-requirements.txt
      - name: Install imaginAIry
        run: pip install imaginAIry
      - name: Create test png via AI
        run: ./aimg.sh imagine "$prompt"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: outputs
