name: aimg
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python with caching
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/checkout@v4
      - name: Print Directory Contents
        run: dir
      - name: Python Setup Tools
        run: pip install setuptools
      - name: Install requirements
        run: pip install -r imaginAIry-requirements.txt
      - name: Install imaginAIry
        run: pip install imaginAIry
      - name: Create test png via AI
        run: sh aimg.sh imagine "cheese in the eifel tower"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: outputs
