name: aimg
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print Directory Contents
        run: dir
      - name: Install requirements
        run: pip install -r imaginAIry-requirements.txt
      - name: Install imaginAIry
        run: pip install imaginAIry
      - name: Create test png via AI
        run: aimg imagine "cheese in the eifel tower"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: outputs
