name: aimg
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Restore cached pip
        id: cache-aimg-restore
        uses: actions/cache/restore@v4
        with:
          path: pipcache
          key: ${{ runner.os }}-aimg
      - name: Python Setup Tools
        run: pip --cache-dir=pipcache install setuptools
      - name: Setup pip cache
        run: pip --cache-dir=pipcache install -r requirements.txt
      - name: Install imaginAIry
        run: pip --cache-dir=pipcache install imaginAIry
      - name: Save pip cache
        id: cache-aimg-save
        uses: actions/cache/save@v4
        with:
          path: pipcache
          key: ${{ steps.cache-aimg-restore.outputs.cache-primary-key }}
      - name: Create test png via AI
        run: aimg imagine "cheese in the eifel tower"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
            name: output
            path: outputs
